// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package crypto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgTicketBaseCtx struct {
	ExpiredTime          uint32   `protobuf:"varint,1,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	IssueTime            uint32   `protobuf:"varint,2,opt,name=issue_time,json=issueTime,proto3" json:"issue_time,omitempty"`
	PayloadCtx           []byte   `protobuf:"bytes,3,opt,name=payload_ctx,json=payloadCtx,proto3" json:"payload_ctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgTicketBaseCtx) Reset()         { *m = MsgTicketBaseCtx{} }
func (m *MsgTicketBaseCtx) String() string { return proto.CompactTextString(m) }
func (*MsgTicketBaseCtx) ProtoMessage()    {}
func (*MsgTicketBaseCtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *MsgTicketBaseCtx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTicketBaseCtx.Unmarshal(m, b)
}
func (m *MsgTicketBaseCtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTicketBaseCtx.Marshal(b, m, deterministic)
}
func (m *MsgTicketBaseCtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTicketBaseCtx.Merge(m, src)
}
func (m *MsgTicketBaseCtx) XXX_Size() int {
	return xxx_messageInfo_MsgTicketBaseCtx.Size(m)
}
func (m *MsgTicketBaseCtx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTicketBaseCtx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTicketBaseCtx proto.InternalMessageInfo

func (m *MsgTicketBaseCtx) GetExpiredTime() uint32 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MsgTicketBaseCtx) GetIssueTime() uint32 {
	if m != nil {
		return m.IssueTime
	}
	return 0
}

func (m *MsgTicketBaseCtx) GetPayloadCtx() []byte {
	if m != nil {
		return m.PayloadCtx
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgTicketBaseCtx)(nil), "crypto.MsgTicketBaseCtx")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0x57,
	0x2a, 0xe5, 0x12, 0xf0, 0x2d, 0x4e, 0x0f, 0xc9, 0x4c, 0xce, 0x4e, 0x2d, 0x71, 0x4a, 0x2c, 0x4e,
	0x75, 0x2e, 0xa9, 0x10, 0x52, 0xe4, 0xe2, 0x49, 0xad, 0x28, 0xc8, 0x2c, 0x4a, 0x4d, 0x89, 0x2f,
	0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0xe2, 0x86, 0x8a, 0x85, 0x64, 0xe6,
	0xa6, 0x0a, 0xc9, 0x72, 0x71, 0x65, 0x16, 0x17, 0x97, 0xa6, 0x42, 0x14, 0x30, 0x81, 0x15, 0x70,
	0x82, 0x45, 0xc0, 0xd2, 0xf2, 0x5c, 0xdc, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0xf1, 0xc9,
	0x25, 0x15, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x5c, 0x50, 0x21, 0xe7, 0x92, 0x8a, 0x24,
	0x36, 0xb0, 0x2b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0x4d, 0xe4, 0x4b, 0x94, 0x00,
	0x00, 0x00,
}
